import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const cabinetGrotesk = localFont({
  src: [
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Black.woff2', weight: '900', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Bold.woff2', weight: '700', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Extrabold.woff2', weight: '800', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Extralight.woff2', weight: '200', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Light.woff2', weight: '300', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../assets/fonts/cabinet-grotesk/CabinetGrotesk-Thin.woff2', weight: '100', style: 'normal' },
  ],
  variable: '--font-cabinet-grotesk',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.variable} bg-gray-100 selection:bg-lime-200 selection:text-black font-cabinet-grotesk overflow-x-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
